server:
  port: 8080
spring:
  application:
    name: "PowerUpCrediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5433}
    database: ${DB_NAME:postgres}
    schema: ${DB_SCHEMA:public}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres123}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080,http://localhost:8081"

routes:
  paths:
    saveUser: "/api/v1/usuarios"
    get-all-users: "/api/v1/usuarios"
    get-user-email-by-id-number: "/api/v1/usuarios/{identificationNumber}"
    log-in: "/auth/api/v1/login"
    validate: "/auth/api/v1/validate/{jwt}"
    get-user-by-email: "/api/v1/usuarios/email/{email}"

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
